### ISSUE TITLE
TEMPLATE: Joining triggers for KEMAS and CSOs

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-malaysia#10]
Implement enrollment mechanisms for the 2 groups of users
KEMAS --> adds to group "kemas"
MASW --> adds to group "csos"

+ validation question (?)

and then they get the same user experience

The trigger START should be disabled after the end of testing at the end of december

**Comment by lauriemarkle** [comment]
For validation: 

Welcome to {ParentText}! How did you enrol in the programme? 
1. Through a KEMAS preschool
2. Through an NGO
3. Social Media
4. A Friend
5. Other

Responses to 1-2 are continued onboarding (with a grouping of the User into the appropriate group). 
Responses 3-5 will currently receive "{ParentText} is currently only available to parents of preschoolers enrolled in KEMAS or local, community preschools. We hope to make {ParentText} available to every Malaysian parent before 2025."

**Comment by fagiothree** [comment]
Clarification needed for the following cases:
* what happens if someone types "kemas" and then selects "ngo"?
* what happens if someone types "masw" and then selects "kemas"?
* If someone types "kemas" or "ngo" and then selects another option, they receive the message "ParentText is currently only available to parents of preschoolers enrolled in KEMAS or local, community preschools. We hope to make ParentText available to every Malaysian parent before 2025." What happens afterwards? are they cut out of the program and cannot rejoin? what if they made a mistake?

**Comment by fagiothree** [comment]
Agreed with Laurie to remove validation question to make onboarding process easier. Validation of IDs will happen comparing data in RapidPro with data collected through FalicitatorApp --> only users with IDs also in FacilitatorApp will be considered for analysis

**Comment by fagiothree** [comment]
Added validation step in joining process
https://docs.google.com/spreadsheets/d/1PHgUhJnZdE0lK6C9teK-hwA6Tf-6Pgj1_OVdxoTgVOA/edit#gid=298038983
defined in
https://docs.google.com/spreadsheets/d/1PHgUhJnZdE0lK6C9teK-hwA6Tf-6Pgj1_OVdxoTgVOA/edit#gid=1377079266
(default version that doesn't do anything)

For Malaysia overwrite defined  in https://docs.google.com/spreadsheets/d/13XUkS7VbGJSg1xiOb2tVOIFcoiochpxqaQeBTk2Ibns/edit#gid=1450843878
that adds users to groups

Need to add triggers to safeguarding json file

**Comment by fagiothree** [comment]
achieved with pull request #23 
separated out START (kept as trigger to rejoin - creating a new category in triggers https://docs.google.com/spreadsheets/d/1PHgUhJnZdE0lK6C9teK-hwA6Tf-6Pgj1_OVdxoTgVOA/edit#gid=751616786) from KEMAS & CSOS (only for joining - in the category START)
