### ISSUE TITLE
TEMPLATE: Add "Next" button in msg lists to slow delivery

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/parenttext-malaysia#12]
In Malaysia, Bahasa Melayu is a very lengthly language. Many lengthy messages sent without a break create the need for back-scrolling.  Edit all block templates including list of messages, so that a NEXT button is included after every 2 consecutive messages

**Comment by fagiothree** [comment]
duplicate issue https://github.com/IDEMSInternational/parenttext-malaysia/issues/14
