### ISSUE TITLE
Place "Next" Button after every 2 consecutive messages

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/parenttext-malaysia#14]
To avoid backscrolling, ensure that a "next" button appears after any two consecutive messages (i.e. after the second, before the third), regardless of flow

<img width="413" alt="image" src="https://github.com/IDEMSInternational/parenttext-malaysia/assets/74552270/6436b48a-9ccb-4ac1-95d1-e84a0b88ecfd">
In the message above, a next button would go after the intro text and the comic.intro

**Comment by fagiothree** [comment]
Need to overwrite the following templates for Malaysia adding "NEXT" as quick reply and a wait for response node:
* **importance_template**: every 2 consecutive messages
* **ltp_activity**: every 2 consecutive messages
* **introduction_template**:  after the first message and every 2 consecutive messages
* **comic_template**: after the intro (if existing)

**Comment by fagiothree** [comment]
Content flow templates redefined as described above in https://docs.google.com/spreadsheets/d/13XUkS7VbGJSg1xiOb2tVOIFcoiochpxqaQeBTk2Ibns/edit#gid=1329498385
