### ISSUE TITLE
Revise User Flow: Home Activity Check-Ins

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/parenttext-malaysia#16]
Home Activity Check-Ins have been re-drafted to invite users to make progress on their goals. 
https://docs.google.com/spreadsheets/d/1ngDMHtkRBGODLwjP1CgGQrdKqW7VWmjoyaEPzkKrx1E/edit#gid=0
Users should receive this message in lieu of the home activity check-in. 
To make this work, the daily interaction flow needs to remove the post-home-activity-check-in response. 

Please update the flow and adapt the WhatsApp template as needed.

**Comment by fagiothree** [comment]
extended data list model as in https://github.com/IDEMSInternational/parenttext-pipeline/commit/5f8b7ed15c13458d221847ceeacaada33ac376e9
extended template https://docs.google.com/spreadsheets/d/1hcH8pFdiHZN0UvZgyv3Zht9ARBTx-VXhNBI2o8L7fHU/edit#gid=1002804942

**Comment by fagiothree** [comment]
Daily interaction algorithm updated as in https://docs.google.com/spreadsheets/d/13XUkS7VbGJSg1xiOb2tVOIFcoiochpxqaQeBTk2Ibns/edit#gid=919584428 to remove home activity check-ins
Logic flow explained in https://app.diagrams.net/#G1VsB0LQSMyz39wyoePNedlIHVhrwCX7HK#%7B%22pageId%22%3A%227bNra7CI3_SvWLEjwH6B%22%7D
