### ISSUE TITLE
Update illustrations and videos

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-malaysia#18]
Update files in firebase from new files on DAM

videos:
https://parentingforlifelonghealth.canto.com/s/HNGB8?viewIndex=0

illustrations:
https://parentingforlifelonghealth.canto.com/s/OS1QR?viewIndex=0

**Comment by fagiothree** [comment]
@istride could you help with the videos? need to compress, check that names are correct and then upload to firebase

**Comment by istride** [comment]
Videos have been processed and uploaded to firebase.

**Comment by fagiothree** [comment]
Images have been downloaded from Canto with lowest quality possible and uploaded to firebase
