### ISSUE TITLE
Bug: Inconsistent Status Bar

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/parenttext-malaysia#26]
In one instance, a participant's progress bar was not consistent. First message said 75%, then it became 25%. 

See Screenshots and further documentation in item 4, here: https://docs.google.com/document/d/1u-pbCSUxLz-vfHCXhdQJYoV-Y5FTVsP5_zk-acBSmNc/edit

**Comment by istride** [comment]
Blocked waiting for research ID of the affected contact, so that we can investigate in RapidPro.
