### ISSUE TITLE
TEMPLATE: Revise flow template for Take a Pause module

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/parenttext-malaysia#7]
Regardless of the requested user experience (text, audio, or video), the Take a Pause module should be received as a video and the comic should be removed.

**Comment by fagiothree** [comment]
defined in content_flow_structure the types "video_for_all" that sends a video to all users and does not have progress tracking emojis. The structure overrides the default structure for the take_a_pause module as specified in https://docs.google.com/spreadsheets/d/13XUkS7VbGJSg1xiOb2tVOIFcoiochpxqaQeBTk2Ibns/edit#gid=0###
